name: Publish website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/gatsby-gh-pages-action
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: dist