name: Publish website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install action dependencies
        run: npm install
        working-directory: ./.github/actions/gatsby-gh-pages-action

      - uses: ./.github/actions/gatsby-gh-pages-action
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: dist